services:
  core:
    build:
      context: .
      dockerfile: ./apps/core/Dockerfile
      target: development
    command: yarn start:dev core
    env_file:
      - ./apps/core/.env
    depends_on:
      - rabbitmq
      - parse_service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
  parse_service:
    build:
      context: .
      dockerfile: ./apps/parse_service/Dockerfile
      target: development
    command: yarn start:dev parse_service
    env_file:
      - ./apps/parse_service/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'